[book]
authors = ["Derek"]
language = "en"
multilingual = false
src = "src"
title = ""

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "/docs/"

[output.html.font]
enable = true
woff = true
